security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

        users_in_memory:
            memory:
                users:
                    username:
                        password: 'mot_de_passe'
                        roles: ['ROLE_UTILISATEUR']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UtilisateurChecker

            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate

            logout:
                path: /logout
                target: app_accueil

    access_control:
        - { path: ^/article/new, roles: ROLE_ADMIN }
        - { path: ^/article/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/article/\d+/delete, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/panier, roles: ROLE_USER }


parameters:
    avatars_directory: '%kernel.project_dir%/public/uploads/avatars'
    images_directory: '%kernel.project_dir%/public/uploads/images'

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
